#!/bin/sh


clear

echo
echo "Compiling Utilities..."
cd Utilities
gcc -m64 -Wall -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -DNO_ASSERTIONS -DSERIAL_REGRID -O -I. -c Utilities.c BasicNumerics.c DateTime.c Failure.c Memory.c Stream.c Projector.c Lambert.c Stereographic.c Mercator.c VoidList.c Grid.c elevation.c RegridQuadrilaterals.c
ls -l *.o
cd ..

echo
echo "Compiling OMISubset..."

# Compile OMISubset:

gcc -m64 -Wall -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -DNDEBUG -DNO_ASSERTINOS -O -I. -IHDF5 -IUtilities -o OMISubset OMISubset.c ReadFile.c Utilities/*.o -L. -lhdf5_hl -lhdf5 -lcurl -lz -ldl -lm -lc
strip OMISubset
ls -l OMISubset
file  OMISubset
ldd   OMISubset

