#!/bin/csh -f
set files = ( \
./acam/src/XDRConvert/Utilities/elevation.c \
./acam/src/XDRConvert/Utilities/elevation.c \
./airnow/src/XDRConvert/Utilities/elevation.c \
./airnow/src/XDRConvert/Utilities/elevation.c \
./aqs/src/XDRConvert/Utilities/elevation.c \
./aqs/src/XDRConvert/Utilities/elevation.c \
./calipso/src/XDRConvert/Utilities/elevation.c \
./calipso/src/XDRConvert/Utilities/elevation.c \
./ceilometer/src/XDRConvert/Utilities/elevation.c \
./ceilometer/src/XDRConvert/Utilities/elevation.c \
./ceilometer/src/CeilometerSubset/Utilities/elevation.c \
./ceilometer/src/CeilometerSubset/Utilities/elevation.c \
./ceilometer/src/Ceilometer2Subset/Utilities/elevation.c \
./ceilometer/src/Ceilometer2Subset/Utilities/elevation.c \
./cmaq/src/XDRConvert/Utilities/elevation.c \
./cmaq/src/XDRConvert/Utilities/elevation.c \
./cmaq/cmaqserver \
./cmaq/cmaqserver \
./cmaq/cmaqserver \
./cmaq/cmaqserver \
./cmaq/cmaqserver \
./cmaq/cmaqserver \
./cmaq/cmaqserver \
./cmaq/cmaqserver \
./cmaq/cmaqserver \
./cmaq/cmaqserver \
./cmaq/cmaqserver \
./cmaq/cmaqserver \
./edm/src/XDRConvert/Utilities/elevation.c \
./edm/src/XDRConvert/Utilities/elevation.c \
./edm/nerrsserver \
./edm/tidalserver \
./faqsd/faqsdserver \
./faqsd/src/XDRConvert/Utilities/elevation.c \
./faqsd/src/XDRConvert/Utilities/elevation.c \
./faqsd/extract \
./gasp/src/XDRConvert/Utilities/elevation.c \
./gasp/src/XDRConvert/Utilities/elevation.c \
./gasp/src/GASPSubset/Utilities/elevation.c \
./gasp/src/GASPSubset/Utilities/elevation.c \
./goesbb/src/XDRConvert/Utilities/elevation.c \
./goesbb/src/XDRConvert/Utilities/elevation.c \
./goes/src/XDRConvert/Utilities/elevation.c \
./goes/src/XDRConvert/Utilities/elevation.c \
./goes/src/GOESSubset/Utilities/elevation.c \
./goes/src/GOESSubset/Utilities/elevation.c \
./hms/src/XDRConvert/Utilities/elevation.c \
./hms/src/XDRConvert/Utilities/elevation.c \
./hrrr/src/XDRConvert/Utilities/elevation.c \
./hrrr/src/XDRConvert/Utilities/elevation.c \
./hysplit/src/HYSPLITSubset/Utilities/elevation.c \
./hysplit/src/HYSPLITSubset/Utilities/elevation.c \
./metar/src/XDRConvert/Utilities/elevation.c \
./metar/src/XDRConvert/Utilities/elevation.c \
./metar/src/METARSubset/Utilities/elevation.c \
./metar/src/METARSubset/Utilities/elevation.c \
./modis/src/XDRConvert/Utilities/elevation.c \
./modis/src/XDRConvert/Utilities/elevation.c \
./mozaic/src/XDRConvert/Utilities/elevation.c \
./mozaic/src/XDRConvert/Utilities/elevation.c \
./mozaic/src/MOZAICSubset/MOZAICSubset.c \
./mozaic/src/MOZAICSubset/Utilities/elevation.c \
./mozaic/src/MOZAICSubset/Utilities/elevation.c \
./omibehrioapi/src/XDRConvert/Utilities/elevation.c \
./omibehrioapi/src/XDRConvert/Utilities/elevation.c \
./omibehr/src/XDRConvert/Utilities/elevation.c \
./omibehr/src/XDRConvert/Utilities/elevation.c \
./omibehr/src/BEHRSubset/Utilities/elevation.c \
./omibehr/src/BEHRSubset/Utilities/elevation.c \
./omi/src/XDRConvert/Utilities/elevation.c \
./omi/src/XDRConvert/Utilities/elevation.c \
./omi/src/OMISubset/Utilities/elevation.c \
./omi/src/OMISubset/Utilities/elevation.c \
./pandora/src/XDRConvert/Utilities/elevation.c \
./pandora/src/XDRConvert/Utilities/elevation.c \
./purpleair/src/XDRConvert/Utilities/elevation.c \
./purpleair/src/XDRConvert/Utilities/elevation.c \
./retigo/download_data \
./rsig/src/XDRConvert/Utilities/elevation.c \
./rsig/src/XDRConvert/Utilities/elevation.c \
./surfmet/src/XDRConvert/Utilities/elevation.c \
./surfmet/src/XDRConvert/Utilities/elevation.c \
./tad/src/XDRConvert/Utilities/elevation.c \
./tad/src/XDRConvert/Utilities/elevation.c \
./tad/src/TADSubset/Utilities/elevation.c \
./tad/src/TADSubset/Utilities/elevation.c \
./tempo/src/XDRConvert/Utilities/elevation.c \
./tempo/src/XDRConvert/Utilities/elevation.c \
./tropomi/src/XDRConvert/Utilities/elevation.c \
./tropomi/src/XDRConvert/Utilities/elevation.c \
./viirs/src/XDRConvert/Utilities/elevation.c \
./viirs/src/XDRConvert/Utilities/elevation.c \
)

foreach f ( $files )
  cat $f | sed 's|/rsig/data|/data|g' | sed 's|/rsig/current||g' > $f.new
  chmod 664 $f
  mv $f.new $f
end

