#!/bin/sh

clear

echo
echo "Compiling subsetdods"
gcc -m64 -Wall -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -DNDEBUG -O -o subsetdods subsetdods.c -lm
strip subsetdods
ls -l subsetdods
file  subsetdods
ldd   subsetdods

ls -Fsalt | head
echo Done

