#!/bin/sh


echo
echo "Compiling Utilities..."
cd Utilities
gcc -m64 -Wall -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -DNO_ASSERTIONS -DSERIAL_REGRID -O -I. -c Utilities.c BasicNumerics.c DateTime.c Failure.c Memory.c Stream.c Projector.c Lambert.c Stereographic.c Mercator.c VoidList.c Grid.c elevation.c RegridQuadrilaterals.c
ls -l *.o
cd ..


# Compile Ceilometer2Subset:

gcc -m64 -Wall -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -DNDEBUG -O -I. -IUtilities -o Ceilometer2Subset Ceilometer2Subset.c ReadData.c ReadFile.c Utilities/*.o -L. -lnetcdf4 -lhdf5_hl -lhdf5 -lcurl -lz -ldl -lm -lc
strip Ceilometer2Subset
ls -l Ceilometer2Subset
file  Ceilometer2Subset
ldd   Ceilometer2Subset

